### ISSUE TITLE
Ejemplos de utilización de la API

### ISSUE THREAD

**Issue by jaimebw** [guemesturb/TheArtist#1]
Buenas! Estoy jugueteando con la clase pero me surgen unas cuantas dudas a la hora de usarla. Podrías ponerme por aquí algún ejemplo de utilización de esta? Cómo la llamas y tal para no modificar la API, o modificarla lo menos posible. Por ahora he conseguido hacer un scatter, pero he tenido que cambiar la clase para poder hacerlo cómo se me ha ocurrido:
```python
TheArtist(latex = False).plot_scatter(df.index,df["sepal length (cm)"],0,0)
```

He quitado Latex porque en mi sistema no lo tengo instalado, y he tenido que llamar el método de ```self.generate_figure_environment()```dentro de ```__init__```.

**Comment by guemesturb** [comment]
Buenas,
Claramente tengo que añadir detalles al README. Te paso un ejemplo con variables dummy:
```python
from artist import TheArtist
x = np.arange(1,10)
y = np.arange(1,20)
z = np.sin(x)
figure = TheArtist(latex=False)
figure.generate_figure_environment(cols=1, rows=2, fig_width_pt=384, ratio='golden', regular=True)
figure.plot_lines(x, y, 0, 0, color='darkblue', linewidth=1, linestyle='-', marker='o')
figure.plot_scatter(x, z, 0, 1, marker='s')
figure.set_labels(['Eje 1', 'Eje V'], 0, 0)
figure.set_labels(['Eje 2', None], 0, 0)
figure.savefig("test", fig_format='pdf', dots_per_inch=1000)
```
La idea es iniciar un objeto con TheArtist y definirlo con generate_figure_environment (principalmente número de paneles y tamaño) y luego ir pintando por paneles. Cualquier duda me comentas por favor.

**Comment by jaimebw** [comment]
Hola Alejandro, he hecho un par de cosillas ya por si le quieres echar un [ojo](https://github.com/jaimebw/TheArtist/tree/jaime). En resumen:
* He creado un setup.py para poder instalarlo como una biblioteca (todavía no le he puesto en Pypi)
* He puesto un par de tests (solo para revisar que no me cargo nada si cambio alguna función) usando PyTest
* He añadido un README un poco más bonito, y que explica cómo instalarlo como una biblioteca
* Una carpeta de ejemplos

Mi idea es desarrollarlo un poquito más, porque me gusta mucho cómo quedan las gráficas y a lo mejor le empiezo a darle un uso más intensivo. Si te parece correcto, hago una PR cuando tenga alguna cosita más 😉

**Comment by guemesturb** [comment]
Está genial! Muchas gracias por el curro! Por supuesto, haz el PR en cuanto lo tengas :)

**Comment by jaimebw** [comment]
Hola Alex, estaba pensando en realizar ciertos cambios a la API:
* Cambiar plot_scatter y plot_lines por scatter y plot (igual que la API de matplotlib)
* Llamar generate_figure_environment dentro de __init__ para que al iniciar el objeto, puedas determinar ya el tamaño de los plots sin tener que llamar al método después
* Cambiar el método save_figure a savefig, para que sea más parecido a matplotlib

Si te parece buena idea, te hago PR cuando lo tenga, y asi ya podrías subirlo a PyPi.

**Comment by guemesturb** [comment]
De acuerdo con todos los cambios

**Comment by jaimebw** [comment]
Epa, ya lo tienes en #2
